name: Sync artifact to S3

on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the GitHub Actions artifact to download.
        required: true
        type: string
      aws-region:
        description: The AWS region containing the destination S3 bucket.
        required: true
        type: string
      destination-prefix:
        default: ''
        description: The S3 key prefix under which to preserve the artifact contents.
        required: false
        type: string
      s3-bucket:
        description: The name of the destination S3 bucket.
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        description: The IAM role to assume using GitHub OpenID Connect.
        required: true

permissions:
  actions: read
  id-token: write

jobs:
  sync:
    name: Sync Artifact
    runs-on: ubuntu-26.04
    steps:
    - name: Download artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ runner.temp }}/s3-sync
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
    - name: Sync artifact
      env:
        ARTIFACT_DIRECTORY: ${{ runner.temp }}/s3-sync
        DESTINATION_PREFIX: ${{ inputs.destination-prefix }}
        S3_BUCKET: ${{ inputs.s3-bucket }}
      run: |
        DESTINATION="s3://$S3_BUCKET"
        if [[ -n "$DESTINATION_PREFIX" ]]; then
          DESTINATION+="/${DESTINATION_PREFIX#/}"
        fi
        aws s3 sync "$ARTIFACT_DIRECTORY/" "${DESTINATION%/}/" --only-show-errors
