name: CI

on:
  pull_request: { }
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  workflows:
    name: Workflows
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        cache: false
        go-version: '1.27.1'
    - name: Check workflows
      run: go run github.com/rhysd/actionlint/cmd/actionlint@v1.7.12
  release:
    name: Release
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release-please.yaml
