name: Verify Go

on:
  workflow_call:
    inputs:
      go-version-file:
        default: go.mod
        description: Path to the Go version file from the working directory.
        required: false
        type: string
      golangci-lint-version:
        default: v2.14.0
        description: The golangci-lint version to install.
        required: false
        type: string
      working-directory:
        default: .
        description: The working directory for Go commands.
        required: false
        type: string

permissions:
  contents: read

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        cache-dependency-path: ${{ format('{0}/go.mod', inputs.working-directory) }}
        go-version-file: ${{ format('{0}/{1}', inputs.working-directory, inputs.go-version-file) }}
    - name: Lint source code
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: ${{ inputs.golangci-lint-version }}
        working-directory: ${{ inputs.working-directory }}
    - name: Check formatting
      run: test -z "$(go fmt ./...)"
      working-directory: ${{ inputs.working-directory }}
    - name: Check dependencies
      run: go mod verify
      working-directory: ${{ inputs.working-directory }}
    - name: Ensure dependencies are tidy
      run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum
        if test -f go.sum && ! git ls-files --error-unmatch -- go.sum >/dev/null 2>&1; then
          >&2 echo "go mod tidy created an untracked go.sum"
          exit 1
        fi
      working-directory: ${{ inputs.working-directory }}
    - name: Vet code
      run: go vet ./...
      working-directory: ${{ inputs.working-directory }}
    - name: Run unit tests
      run: go test -cover -race -v ./...
      working-directory: ${{ inputs.working-directory }}
